"""
Coordinator Agent
Synthesizes outputs from all specialized agents into a unified analytical report.
"""

import json
from datetime import datetime
from pathlib import Path


class CoordinatorAgent:
    def __init__(self):
        print("[CoordinatorAgent] Initialized.")

    def _format_list(self, items: list, indent: int = 2) -> str:
        if not items:
            return "  None identified."
        prefix = " " * indent
        return "\n".join(f"{prefix}- {item}" for item in items)

    def synthesize(
        self,
        summary_output: dict,
        citation_output: dict,
        methodology_output: dict,
        critical_output: dict,
        paper_source: str = "Unknown",
    ) -> str:
        """Combine all agent outputs into a structured markdown report."""

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        title = citation_output.get("paper_title", "Unknown Paper")

        report = f"""# Multi-Agent Scientific Paper Analysis Report
**Generated:** {timestamp}  
**Source:** {paper_source}  
**Detected Title:** {title}

---

## 1. Paper Summary
{summary_output.get("summary", "Summary not available.")}

---

## 2. Citation Analysis
- **References found:** {citation_output.get("num_references", 0)}
- **Knowledge graph:** {citation_output.get("graph_nodes", 0)} nodes, {citation_output.get("graph_edges", 0)} edges
- **Graph saved to:** `{citation_output.get("graph_image", "N/A")}`

### Sample References
{self._format_list(citation_output.get("references", [])[:5])}

---

## 3. Methodology Extraction
### Datasets Identified
{self._format_list(methodology_output.get("datasets_identified", []))}

### Evaluation Metrics
{self._format_list(methodology_output.get("evaluation_metrics", []))}

### Model Architectures / Techniques
{self._format_list(methodology_output.get("model_architectures", []))}

---

## 4. Critical Analysis
### Limitations
{self._format_list(critical_output.get("limitations", []))}

### Future Research Directions
{self._format_list(critical_output.get("future_directions", []))}

---

## 5. Agent Summary
| Agent | Status | Key Output |
|-------|--------|------------|
| Summarization | ✅ Complete | {len(summary_output.get("summary",""))} chars |
| Citation Analysis | ✅ Complete | {citation_output.get("num_references", 0)} references |
| Methodology Extractor | ✅ Complete | {len(methodology_output.get("datasets_identified",[]))} datasets, {len(methodology_output.get("evaluation_metrics",[]))} metrics |
| Critical Analysis | ✅ Complete | {critical_output.get("num_limitations_found",0)} limitations, {critical_output.get("num_future_directions_found",0)} future directions |
| Coordinator | ✅ Complete | Report synthesized |

---
*Report generated by Multi-Agent Scientific Paper Analysis System*
"""
        return report

    def run(
        self,
        summary_output: dict,
        citation_output: dict,
        methodology_output: dict,
        critical_output: dict,
        paper_source: str = "Unknown",
        output_dir: str = "outputs",
    ) -> dict:
        print("[CoordinatorAgent] Synthesizing final report...")
        report_md = self.synthesize(
            summary_output, citation_output, methodology_output, critical_output, paper_source
        )

        # Save report
        report_path = str(Path(output_dir) / "analysis_report.md")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_md)

        # Save raw JSON of all outputs
        json_path = str(Path(output_dir) / "raw_outputs.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(
                {
                    "summary": summary_output,
                    "citations": citation_output,
                    "methodology": methodology_output,
                    "critical": critical_output,
                },
                f,
                indent=2,
            )

        print(f"[CoordinatorAgent] Report saved to {report_path}")
        return {"report_path": report_path, "json_path": json_path, "report": report_md}